parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     test_project
    database_user:     postgres
    database_password: postgres

    mailer_transport:  gmail
    mailer_host:       localhost
    mailer_user:       ragetankrobot@gmail.com
    mailer_password:   R@g3+anX

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
