# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_user_bundle:
    resource: "@RageTankUserBundle/Resources/config/routing.yml"