services:
    ragetank_user.form.type.registration:
        class: RageTank\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ragetank_user_registration }

    ragetank_user.form.handler.registration:
        class: RageTank\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator", "@service_container"]
        scope: request
        public: false